//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NESS.VoucherManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CO = Concediu de odihna</string>
  <string>ZCBIMP = Concediu medical</string>
  <string>CFP = Concediu fara plata</string>
  <string>CEV = Concediu evenimente deosebite</string>
  <string>NEM = Absenta nemotivata</string>
  <string>IP = Invoire platita</string>
  <string>PATERN = Concediu paternal</string>
  <string>STUD = Concediu studii platite</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OutOfOfficeOperations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OutOfOfficeOperations"]));
            }
        }
    }
}
